import { createElement } from 'lwc';
import Dap27June2024_platform_event from 'c/dap27June2024_platform_event';

describe('c-dap27-june2024-platform-event', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-dap27-june2024-platform-event', {
            is: Dap27June2024_platform_event
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});