import { createElement } from 'lwc';
import TetSeptember2023_NewsApi from 'c/tetSeptember2023_NewsApi';

describe('c-tet-september2023-news-api', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-tet-september2023-news-api', {
            is: TetSeptember2023_NewsApi
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});