import { createElement } from 'lwc';
import DapPracticePaper1_OwnerChange from 'c/dapPracticePaper1_OwnerChange';

describe('c-dap-practice-paper1-owner-change', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-dap-practice-paper1-owner-change', {
            is: DapPracticePaper1_OwnerChange
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});